### ISSUE TITLE
configure netMHC

### ISSUE THREAD

**Issue by 0x1orz** [openvax/mhctools#141]
when i test  `mhctools --sequence SIINFEKL SIINFEKLQ --mhc-predictor netmhc --mhc-alleles A0201`,I got the error ---FileNotFoundError: [Errno 2] No such file or directory: 'netMHC'. 

How to configure the command lines? even i use alias  netMHC or export  netMHC  the netMHC real path, that could not be soved

**Comment by sheljoy** [comment]
I solved by `export PATH=$PATH:/path/to/netMHC`. if it can be configured in a configure file like config.ini ,it is would be more friendly for users.

**Comment by zakimolvi** [comment]
@sheljoy In case you didn't solve this yet, it sounds like your PATH variable may not include the directory of your local netMHC installation. This is similar to #8 .

Make sure your PATH variable includes the directory of your local NetMHC installation(s), e.g when I type:
`>echo $PATH`
outputs:
`...:/Users/zaki/netMHCpan-4.0:/Users/zaki/netMHC-4.0:..`

**Comment by iskandr** [comment]
User support question, answered in comments. The CLI now also has `--mhc-predictor-path` for specifying executable paths.
